[workspace]
members = [
    "run-wasm",
    "winit",
    "winit-core"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["serde_derive"] }
winit-core = { path = "./winit-core", default-features = false, features = ["std"] }
